#ifndef MODBUSTCP_GLOBAL_H
#define MODBUSTCP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODBUSTCP_LIBRARY)
#  define MODBUSTCPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODBUSTCPSHARED_EXPORT Q_DECL_IMPORT
#endif

#define ERROR_CONST			5

#endif // MODBUSTCP_GLOBAL_H
